config/routes.rb
Rails.application.routes.draw do

  namespace :static_pages, path: '/' do
    get 'about'
    get 'health_check'
  end

  get 'target_pace/calc'

  root 'target_pace#index'

  # API
  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/' do
    resources :target_paces, only: :index

    resources :run_types, only: :index
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api/api_response_base.rb
module API
  class ApiResponseBase
    include ResponseBoilerPlate
  end
end

app/models/api/api_response_boiler_plate.rb
module API

  # A class that should be included in all of our API responses.
  # Contains useful info like the api version and the UTC timestamp
  module ResponseBoilerPlate
    attr_reader :about
    def initialize
      @about = BoilerPlate.new
    end

    private
    class BoilerPlate
      attr_reader :api_version, :legal, :time_stamp_utc
      def initialize
        @legal = 'RunbyPace (c)2017. By Ty Walls. https://runbypace.com'
        @api_version = 'v1'
        @time_stamp_utc = Time.now.utc
      end
    end
  end
end

app/models/api/api_response_error.rb
module API
  class ApiResponseError < ApiResponseBase
    attr_reader :error, :usage
    def initialize(error_message, usage_message)
      super()
      @error = error_message
      @usage = usage_message
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pace_calcs.rb
require 'runby_pace'

class TargetPaceData
  attr_reader :five_k_time, :run_type, :pace_data_km, :pace_data_mi, :kph, :mph

  def initialize(five_k_time, run_type, pace_data_km, pace_data_mi, kph, mph)
    @five_k_time = five_k_time
    @run_type = run_type
    @pace_data_km = pace_data_km
    @pace_data_mi = pace_data_mi
    @kph = kph
    @mph = mph
  end
end

class PaceCalcs
  def calc(five_k_time, run_type, units)
    run_type = Runby::RunTypes.new_from_name(run_type)
    pace_data_km = run_type.lookup_pace(five_k_time, :km)
    pace_data_mi = run_type.lookup_pace(five_k_time, :mi)

    speed_kph = pace_data_km.as_speed_range.to_s
    speed_mph = pace_data_mi.as_speed_range.to_s

    five_k_time_formatted = Runby::RunbyTime.new(five_k_time).to_s
    @pace = TargetPaceData.new(five_k_time_formatted, run_type, pace_data_km.to_s, pace_data_mi.to_s, speed_kph, speed_mph)
  end

  private

  def get_distance_units(units)
    case units
      when 'imperial' then :mi
      when 'metric' then :km
      else :km
    end
  end

end

app/controllers/api/application_controller.rb
module API
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
  end
end

app/controllers/api/run_types_controller.rb
module API

  require 'api/api_response_boiler_plate'

  class RunTypesController < ApplicationController
    class RunTypesResponse < ApiResponseBase
      attr_reader :run_types
      def initialize(run_types)
        super()
        @run_types = run_types
      end
    end

    def index
      response = RunTypesResponse.new(Runby::RunTypes.all)
      render json: response, status: 200
    end
  end
end

app/controllers/api/target_paces_controller.rb
module API

  require 'api/api_response_boiler_plate'

  class TargetPacesController < ApplicationController

    class TargetPaceUsageErrorResponse < ApiResponseError
      def initialize(error)
        usage = "Provide five_k_time and run_type, like this: 'target_paces?five_k_time=21:30;run_type=LongRun'"
        super(error, usage)
      end
    end

    class TargetPaceResponse < ApiResponseBase
      attr_reader :best_five_k_time, :run_type
      attr_reader :target_pace_km, :target_pace_mi
      attr_reader :target_speed_kph, :target_speed_mph

      def initialize(pace_calculation)
        super()
        @best_five_k_time = pace_calculation.five_k_time
        @run_type = pace_calculation.run_type.description
        @target_pace_km = pace_calculation.pace_data_km
        @target_pace_mi = pace_calculation.pace_data_mi
        @target_speed_kph = pace_calculation.kph
        @target_speed_mph = pace_calculation.mph
      end
    end

    def index
      error = ''
      error = "#{error}Missing 'five_k_time';" unless params[:five_k_time]
      error = "#{error}Missing 'run_type';" unless params[:run_type]
      unless error.empty?
        render json: TargetPaceUsageErrorResponse.new(error), status: 400
        return
      end
      units = params[:units]
      pace = PaceCalcs.new.calc(params[:five_k_time], params[:run_type], units)
      target_pace = TargetPaceResponse.new pace
      render json: target_pace, status: 200
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
    @active_nav = 'about'
  end

  def health_check
    render inline: '<!DOCTYPE html><html><body><h1>¯\\_(ツ)_/¯</h1></body></html>'
  end
end

app/controllers/target_pace_controller.rb
require 'pace_calcs'

class TargetPaceController < ApplicationController

  def index
    @activated_toggles = []
    @units = 'imperial'
    @active_nav = 'index'
  end

  def calc
    respond_to do |format|
      @units = 'imperial'
      @pace = PaceCalcs.new.calc(params[:five_k_time], params[:run_type], @units)
      @activated_toggles = params[:activated_toggles].split(';')
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def class_list_if(condition, class_list)
    if condition
      " class=#{class_list} "
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/target_pace_helper.rb
require 'runby_pace'

module TargetPaceHelper

  @runs = Runby::RunTypes

  def self.all_run_types
    run_types = []
    @runs.all.each do |run_type|
      run_types << [@runs.new_from_name(run_type).description, run_type]
    end
    run_types
  end

  def self.run_type_explanations
    explanations = ''
    @runs.all.each do |run_type|
      explanations << "\"#{run_type}\": \"#{@runs.new_from_name(run_type).explanation.tr('"', '') }\",\n"
    end
    explanations
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#ab2b03">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="🏃 Runby Pace">
<meta name="application-name" content="🏃 Runby Pace">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">
      Runby Pace &copy; <%= Date.today.year %> Ty Walls <a href="https://twitter.com/tygertec">@tygertec</a>
    </p>
  </div>
</footer>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">&#x1F3C3; Runby Pace</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li role="presentation" <%= class_list_if(@active_nav == 'index', 'active') %>"><a href="/">Home</a></li>
        <li role="presentation" <%= class_list_if(@active_nav == 'about', 'active') %>><%= link_to('About','/about') %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="author" content="Ty Walls @tygertec">
    <title>&#x1F3C3; Personalized training pace calculator » Runby Pace </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'application/favicon' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script>
        <%- if Rails.env.production? -%>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', '<%= Rails.application.config.google_analytics_id %>', 'auto');
        <%- else -%>
          function ga() { console.log("Google Analytics disabled in Development environment"); }
        <%- end -%>
    </script>

  </head>

  <body>
    <%= yield %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="<%= javascript_path 'google_analytics' %>"></script>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container">

  <%= render 'navbar' %>

  <div class="jumbotron">
    <h1>About Runby Pace</h1>
    <p class="lead">What is this "Runby Pace" thing anyway? Can you eat it? And how do you pronounce it?</p>
  </div>

  <div class="row marketing">
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title">Contents</h2>
        </div>
        <div class="panel-body">
          <ul class="list-unstyled">
            <li><%= link_to('What is Runby Pace', '#what_is_runby_pace') %></li>
            <ul>
              <li><%= link_to('How do you pronounce "Runby"?', '#pronunciation') %></li>
              <li><%= link_to('What is the etymology of "Runby Pace"?', '#etymology') %></li>
            </ul>
            <li><%= link_to('Why I created Runby Pace', '#why_created') %></li>
            <ul>
              <li><%= link_to('A shout out to an inspiring running book', '#build_your_running_body') %></li>
            </ul>
            <li><%= link_to('Development status and the future of Runby Pace', '#development_status') %></li>
            <ul>
              <li><%= link_to('Reporting bugs', '#reporting_bugs') %></li>
            </ul>
            <li><%= link_to('This is great! Can I buy you a beer?', '#donate') %></li>
          </ul>
        </div>
      </div>

      <h2 id="what_is_runby_pace">What is Runby Pace?</h2>
      <p>Runby Pace is a Pace calculator for running. To use it, just enter your time for a recent 5K race, choose your desired type of run, and it will spit out the pace you should target (with your doctor's approval of course). You only have to enter your 5k time once; Runby Pace will remember it the next time you visit the app. Just don't forget to update your 5K time as you get faster!</p>

      <h3 id="pronunciation">How do you pronounce "Runby"?</h3>
      <p>"Runby" is pronounced like "rugby", or "run&middot;bee" if you aren't familiar with rugby.</p>

      <h3 id="etymology">What is the etymology of "Runby Pace"?</h3>
      <p>If you take the word "ruby" and stuff an "n" in the middle, you get "runby".</p>
      <p>Why did we start with a ruby? Rubies are valuable stones and they are red. Your heart is a pretty valuable organ and it's red too. Um yeah, actually I wrote the <a href="https://github.com/tygerbytes/runby-pace">core logic</a> for Runby Pace in a programming language called Ruby, and I'm just not that creative.</p>

      <h2 id="why_created">Why I created Runby Pace</h2>
      <p>I code. I run. Running helps me write better code and just feel better in general. I even felt inspired to <a href="https://tygertec.com/run-better-code/">write an entire article</a> on the subject of running and programming.</p>
      <p>A good running program incorporates runs at varying paces. Depending on your personal level of fitness, you might run at a pace of 10 minutes per mile during your weekly long run, but throw down a blistering 5:30 per mile while running track repeats. The difficult part is knowing which pace <em>you</em> should be running at.</p>
      <p>There are various pace tables that help you find your pace for a given type of run. Usually they center around a recent PR in a 5K or 10K race. There are fairly accurate mathematical formulae which <a href="http://www.hillrunner.com/calculators/raceconversion.php">predict your likely performance</a> in one distance based on your actual performance in another distance. These formulae are used to create these handy pace charts.</p>
      <p>The pace charts are immensely helpful. But... they are clunky and time-consuming. When I'm trying to run out the door at 5AM I need things to be as easy as possible. I wrote Runby Pace to fill that need.</p>

      <h3 id="build_your_running_body">A shout out to an inspiring running book</h3>
      <p>The book that taught me the most about running and got me started with more advanced pacing was <a href="http://amzn.to/2gKxHXG">Build Your Running Body, by Pete Magill</a>. I highly recommend it. For amateur runners like me, this could be the only running book you ever read.</p>


      <h2 id="development_status">Development status and the future of Runby Pace</h2>
      <p>Runby Pace is still under development. You've heard of Version 2.0? Runby Pace is something like Version 0.2. So expect a few bugs, incomplete features, as well as NEW features added periodically. (Ooh, exciting!)</p>
      <p>As I find the time I plan on creating mobile apps as well as an API to facilitate pace calculations the world over. I'm up for anything that streamlines that first step out the front door!</p>

      <h3 id="reporting_bugs">Reporting bugs</h3>
      <p>Did I mention Runby Pace was still in its infancy? :) There will be bugs, so feel free to report them. When reporting a bug, try to be specific as possible in describing the problem. Also, let me know if you're using the web app or one of the forthcoming mobile apps. I will respond as soon as I can, but it could take a while. I work on this for fun in my very limited free time.</p>

      <table class="table">
        <tr>
          <td>Twitter</td>
          <td><a href="https://twitter.com/runbypace">@runbypace</a></td>
        </tr>
        <tr>
          <td>Email</td>
          <td>runbypace at gmail dot com</td>
        </tr>
      </table>

      <h2 id="donate">This is great! Can I buy you a beer?</h2>
      <p>Though I don't drink much alcohol because of its negative impact on my training, I do find it hard to resist a fine red when paired with the right meal. ;) You can contribute to my efforts at <a href="https://paypal.me/tygerbytes/25">paypal.me/tygerbytes</a></p>

    </div>

    <div class="col-md-6">
        <figure>
          <%=image_tag('half_marathon.jpg', class: 'img-responsive img-rounded', alt: 'Almost there! Ty toward the end of the Staten Island half marathon.') %>
          <figcaption class="center">
            Slogging it close to the finish of a half-marathon.
          </figcaption>
        </figure>
    </div>
  </div>

</div>

<%= render 'footer' %>

<script src="<%= javascript_path 'myscript' %>"></script>

app/views/target_pace/_index.js.erb
(function() {
    "use strict";

    function setRunTypeExplanation(run_type_name) {
        var run_type_explanation = {
            <%=	raw(TargetPaceHelper.run_type_explanations) %>
        };
        var explanation = document.getElementById('run_type_explanation');
        explanation.innerHTML = run_type_explanation[run_type_name];
    }

    function selectedRunType() {
        return document.getElementById('run_type').value;
    }

    $('[name="run_type"]').on("change", function () {
        setRunTypeExplanation(selectedRunType())
    });

    setRunTypeExplanation(selectedRunType());
})();

app/views/target_pace/calc.html.erb
<div class="container">

  <%= render 'navbar' %>

  <div class="jumbotron">
    <p>To fully benefit from your <strong><%= @pace.run_type.description %></strong>, your pace should be</p>
    <h1><%= @pace.pace_data_mi %></h1>
  </div>

  <div class="col-lg-12">
    <p>Would you like to help make Runby Pace better?</p>
    <ul>
      <li>Suggest features: <a href="https://twitter.com/runbypace">@runbypace</a></li>
      <li>Donate: <a href="https://paypal.me/tygerbytes/5">paypal.me/tygerbytes</a></li>
    </ul>
  </div>


</div>

<%= render 'footer' %>

app/views/target_pace/calc.js.erb
$("#calculated_targets").html("<%= escape_javascript(render partial: 'calc', locals: { pace: @pace, activated_toggles: @activated_toggles } )%>");

$("#print_preview_button").html("<%= escape_javascript(link_to 'Print preview', target_pace_calc_url(@_request.parameters), class: 'btn btn-info')%>");

app/views/target_pace/index.html.erb
<div class="container">

  <%= render 'navbar', locals: {active_nav: 'index'} %>

  <div class="jumbotron">
    <h1>How hard should you run today?</h1>
  </div>

  <div class="row marketing">
    <div class="col-md-12">
      <div id="calc_pace">
        <%= form_tag('/target_pace/calc', method: :get) do %>
          <%= hidden_field_tag(:activated_toggles, '') %>
          <div class="form-group">
            <%= label_tag(:five_k_time, 'I can run a 5K in:') %>
            <div class="input-group">
              <span class="input-group-addon"><span class="glyphicon glyphicon-heart-empty"></span></span>
              <%= text_field_tag(:five_k_time, '', {:class => 'form-control', :placeholder => 'Your most recent 5K race time; example, 21:30'}) %>
            </div>
            <div class="text-muted">Your finishing time for a recent race is an excellent indicator of your VO2 Max and overall fitness. This helps us prescribe the right paces for your unique body.</div>
          </div>
          <div class="form-group">
            <%= label_tag(:run_type, 'Today, I plan on running:') %>
            <div class="input-group">
              <span class="input-group-addon">&#x1F3C3;</span>
              <%= select_tag(:run_type, options_for_select(TargetPaceHelper::all_run_types, :DistanceRun), {:class => 'form-control'}) %>
            </div>
            <div class="text-muted" id="run_type_explanation">What exciting adventure will your run lead you on today?</div>
          </div>
          <div class="form-group text-center">
            <%= submit_tag('Get my pace', {:class => 'btn btn-primary btn-lg'}) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>


</div>

<%= render 'footer' %>

<script src="<%= javascript_path 'myscript' %>"></script>

<script>
  <%= render 'index.js' %>
</script>